import matplotlib.pyplot as plt
import numpy as np

# Plotting settings
plt.rc('font', family='serif', serif='Times')
plt.rc('text', usetex=True)
plt.rc('xtick', labelsize=10)
plt.rc('ytick', labelsize=10)
plt.rc('axes', labelsize=10)

# n_segments = np.array([14, 9, 6, 4, 3, 2, 1])
# threshold = np.array([0.041, 0.042, 0.043, 0.0432, 0.0435, 0.046, 0.06])
# position_error = np.array([1.080e-4, 3.459e-4, 9.312e-4, 1.630e-3, 5.815e-3, 1.598e-2, 1.941e-2])
# orientation_error = np.array([0.145, 0.454, 1.504, 2.158, 5.804, 19.306, 22.524])

n_segments = np.array([9, 8, 6, 4, 3, 2])
threshold = np.array([0.0623, 0.063, 0.0637, 0.064, 0.065, 0.067])
position_error = np.array([0.000634, 0.000935, 0.00138, 0.002698, 0.0119, 0.0146])
orientation_error = np.array([0.5903, 0.75, 1.0105, 3.1075, 10.865, 12.793])

# fig, ax = plt.subplots(1,1)
# fig.set_size_inches(5, 5 / 1.618 )
# ax.plot(n_segments, position_error, 'o--')
# ax.grid(True)
# ax.set_ylabel(r'Position error $e_p$ [m]')
# ax.set_xlabel('Number of segments')
# ax2 = ax.twiny()
# ax2.set_xlim(ax.get_xlim())
# ax2.set_xticks(n_segments)
# ax2.set_xticklabels(["%.4f" % z for z in threshold])
# ax2.set_xlabel('Threshold')
# plt.show()
# plt.savefig('pareto_front_pac_pos.pdf', bbox_inches='tight')

fig, ax = plt.subplots(1,1)
fig.set_size_inches(5, 5 / 1.618 )
ax.plot(n_segments, position_error, 's--', color='C0')
ax.grid(True)
ax.set_ylabel(r'Position error $e_p$ [m]', color='C0')
ax.set_xlabel('Number of segments')
ax.tick_params(axis='y', labelcolor='C0')
ax2 = ax.twiny()
ax2.set_xlim(ax.get_xlim())
ax2.set_xticks(n_segments)
ax2.set_xticklabels(["%.4f" % z for z in threshold])
ax2.set_xlabel('Threshold')
ax3 = ax.twinx()
ax3.set_ylabel(r'Orientation error $e_{\theta}$ [rad]', color='C1')
ax3.plot(n_segments, orientation_error*np.pi/180, 'o--', color='C1')
# ax3.grid(True)
ax3.tick_params(axis='y', labelcolor='C1')
# fig.set_size_inches(3.487, 3.487 / 1.618 )
plt.show()
plt.savefig('pareto_front_pac.pdf', bbox_inches='tight')

# fig, ax = plt.subplots(1,1)
# fig.set_size_inches(5, 5 / 1.618 )
# ax.plot(n_segments, orientation_error*np.pi/180, 'o--')
# ax.grid(True)
# ax.set_ylabel(r'Orientation error $e_{\theta}$ [rad]')
# ax.set_xlabel('Number of segments')
# ax2 = ax.twiny()
# ax2.set_xlim(ax.get_xlim())
# ax2.set_xticks(n_segments)
# ax2.set_xticklabels(["%.4f" % z for z in threshold])
# ax2.set_xlabel('Threshold')
# plt.show()
# plt.savefig('pareto_front_pac_ori.pdf', bbox_inches='tight')

# fig, ax = plt.subplots(1,1)
# ax.plot(threshold, orientation_error*np.pi/180, 'o--')
# ax.grid(True)
# ax.set_ylabel('Orientation error [deg]')
# ax.set_xlabel('Threshold')
# plt.show()

# fig, ax = plt.subplots(1,1)
# ax.plot(n_segments, position_error, 'o--')
# ax.grid(True)
# ax.set_ylabel('Position error [m]')
# ax.set_xlabel('Number of segments')
# plt.show()

# fig, ax = plt.subplots(1,1)
# ax.plot(n_segments, orientation_error*np.pi/180, 'o--')
# ax.grid(True)
# ax.set_ylabel('Orientation error [deg]')
# ax.set_xlabel('Number of segments')
# plt.show()